### ISSUE TITLE
The function destroyAll fails with error

### ISSUE THREAD

**Issue by penguinpowernz** [strongloop/loopback-connector-redis#44]
When running `destroyAll` this error is returned:

```
     TypeError: Cannot read property 'length' of undefined
      at BridgeToRedis.all (lib/redis.js:513:18)
      at BridgeToRedis.destroyAll (lib/redis.js:631:10)
```

**Comment by smumu** [comment]
Hi,

I have a similar problem:
```
/var/app/current/node_modules/loopback-connector-redis/node_modules/redis/index.js:602
                throw err;
                ^

TypeError: Cannot read property 'id' of null
    at /var/app/current/node_modules/loopback-connector-redis/lib/redis.js:635:61
    at /var/app/current/node_modules/loopback-connector-redis/node_modules/async/lib/async.js:567:21
    at /var/app/current/node_modules/loopback-connector-redis/node_modules/async/lib/async.js:246:17
    at /var/app/current/node_modules/loopback-connector-redis/node_modules/async/lib/async.js:122:13
    …
```

So same function (`BridgeToRedis.prototype.destroyAll`), not really the same error.

It makes the server crashing, so if you have any idea on how to catch this error and at least prevent the crash, it would be great!

**Comment by penguinpowernz** [comment]
Hey @smumu if you set your dep in your package.json to `penguinpowernz/loopback-connector-redis#44-fix-destroy-all` does your problem go away?

**Comment by vjtc0n** [comment]
Hello @penguinpowernz ,

I tried to use your fix-destroy-all, but it seemed not working for me.

For examples, I have a PersistedModel: Comment which has a field: "content": type "string".
Firstly, I used where: { content: content }, it returned error: 

Error: Comment: no indexes found for content impossible to sort and filter using redis connector

After that, I added "index": true to "content", but it didn't destroy anything.
Did I do something wrong ?

Thank you.

**Comment by jareilly** [comment]
We are running into this issue #44. What is the status for the fix? Was the fix ever verified, to be merged into master?

And what's the status for the loopback-connector-redis in general?
The last Issues and Changes are from ~2 years ago.

**Comment by koneapi** [comment]
It would be good to get the fixes like this that are in the master branch into an official NPM release?
The latest NPM release (0.1.0) doesn't contain fixes like this one.

https://groups.google.com/forum/#!topic/loopbackjs/ODqlYaipnjI

**Comment by koneapi** [comment]
I think it would be good to get fixes like this one that are in the master branch into an official NPM release. The last NPM release (0.1.0) doesn't contain them. Is there a way I can help make that to happen :-)?

https://groups.google.com/forum/#!topic/loopbackjs/ODqlYaipnjI
